title: LEEMINJOO
description: Data Science
url: "https://leeminjoo.github.io"
author: Minjoo Lee
avatar: /logo.png
email: eminj1997@naver.com
location: Seoul, Republic of Korea
skin: daylight
date_format: '%b %-d, %Y'

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-remote-theme

remote_theme: ngzhio/jekyll-theme-hamilton

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
google_analytics: G-7VW7G33FBB

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
disqus: leeminjoo-blog

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
logo: logo.png
social:
  name: Minjoo Lee
  links:
    - https://github.com/LEEMINJOO
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
