title: Dionatan Resende
description: Portf√≥lio.
author: Dionatan Diego
avatar: /logo.png
email: dionatanderesende@gmail.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: dionatandiego11
  card: summary
logo: logo.png
social:
  name: Shangzhi Huang
  links:
     - https://twitter.com/dionatandiego11
    # - https://www.facebook.com/ngzhio
    - https://github.com/dionatandiego11
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: pt-br
